### ISSUE TITLE
logback-test.xml overrides logback.xml of any application using this as a library

### ISSUE THREAD

**Issue by NRBPerdijk** [ollls/zio-tls-http#37] opened 2023-06-20 09:57 UTC
Hello `zio-tls-http` maintainers!

Thank you for your work so far!

We are currently investigating using your library to establish `TCP/TLS` connections from a ZIO application (so without the `HTTP` layer), but when we included your library as a dependency, our logging setup exploded. A bit of snooping around uncovered that the `logback-test.xml` you keep in your `main/resources` folder is to blame: it ends up on the classpath (because it's in `main/resources`) and due to logbacks precedence rules, it takes precedence over any defined `logback.xml` in the main project, effectively negating it.

Can this file be moved to the test folder instead? I imagine the Readme also needs a bit of an update then.

Kind regards,
Nathan

**Comment by ollls** [comment] 2023-06-20 18:53
Please, test with   "io.github.ollls" %% "zio-tls-http" % "2.0.1"
2.0.1 needs ZIO 2.0.15 and scala 3.3.0.  In 2.0.1 logback-test renamed to logback.

As a workaround: you can rename your top level logback.xml to logback-test.xml to override.

**Comment by NRBPerdijk** [comment] 2023-06-27 08:50
Thanks, we'll try the new version soon.

We did end up renaming `logback-test.xml` in the meanwhile as an override. That works indeed.

**Comment by jeanmarc** [comment] 2023-10-16 04:51
Hi, a co-worker of Nathan here. We've been successfully using your 2.0.1 version over the past months, using a main `logback.xml` file. The issue is indeed fixed in that version. We hope to se it being officially released soon.

**Comment by ollls** [comment] 2023-10-23 16:36
Yes, it's in a pipeline. We publish it soon. Thank you.

**Comment by ollls** [comment] 2023-12-21 20:52
2.0.1 is published

**Closed as completed** 2023-12-21 20:52 UTC
